export const SET_MODAL = 'SET_MODAL';
export const PREVIEW_PARAMETER = 'PREVIEW_PARAMETER';
export const CLEAR_PREVIEWED_PARAMETER = 'CLEAR_PREVIEWED_PARAMETER';
export const SET_ROUTER_COLLAPSED = 'SET_ROUTER_COLLAPSED';

