export const SET_MASTER_OUTPUT = 'SET_MASTER_OUTPUT';
export const CONNECT_NODES = 'CONNECT_NODES';
export const DISCONNECT_NODES = 'DISCONNECT_NODES';
export const INSERT_NODE = 'INSERT_NODE';
export const SET_PARAMETER = 'SET_PARAMETER';

