export const SET_MASTER_OUTPUT = 'SET_MASTER_OUTPUT';
export const SET_INLET_CONNECTION = 'INSERT_INLET_CONNECTION';
export const SET_OUTLET_CONNECTION = 'INSERT_OUTLET_CONNECTION';
export const INSERT_NODE = 'INSERT_NODE';
export const PREVIEW_PARAMETER = 'PREVIEW_PARAMETER';
export const SET_PARAMETER = 'SET_PARAMETER';
export const ADD_BUS = 'ADD_BUS';
export const REMOVE_NODE = 'REMOVE_NODE';
export const RESET_ALL = 'RESET_ALL';

